config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  resources :categories
  
  resources :posts do
    resources :comments
  end

  root 'pages#home'
  
  get 'about',to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'blog', to: 'pages#blog'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 240}
  validates :content, presence: true, length:{minimum: 7, maximum: 1000}

  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3, maximmum: 255}
  validates :message, presence: true, length: {minimum: 7, maximum: 2000}
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 240}
  validates :content, presence: true, length: {minimum: 7, maximum: 15000}

  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy

  # Model for Search result
  def self.search(search)
    if search
      where(["title LIKE ?", "%#{search}%"]).order('created_at DESC')
    else
      all.order('created_at DESC')
    end
  end

  has_one_attached :thumbnail
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: :true, uniqueness: { case_sensitive: false } # Here is the uniqueness, yes

  has_many :posts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me] # This line sets a variable added_attrs with the attributes
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs # This line says use the attributes for signup
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs # This line says use the attributes for update account
  end
end

# Lets open up config/initializers/devise.rb line 43

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :cat_find, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @cats = Category.all
  end

  def new
    @cat = Category.new
  end

  def create
    @cat = Category.new(cat_params)
    if @cat.save
      flash[:success] = "Category created successfully."
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @cat.update(cat_params)
      flash[:success] = "Category updated successfully."
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @cat.destroy
    flash[:danger] = "Category deleted successfully"
    redirect_to categories_path
  end


  private
  def cat_params
    params.require(:category).permit(:name, :content)
  end

  def cat_find
    @cat = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end


  private
  def comment_params
    params.require(:comment).permit(:name, :message)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Post.all.order('created_at DESC').limit(4)
  end

  def about
  end

  def contact
  end

  def blog
    # @posts = Post.all.paginate(:page => params[:page], :per_page => 3)
    @posts = Post.search(params[:search]).paginate(:page => params[:page], :per_page => 3)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_postid, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  def index
    @posts = Post.where(:user_id => current_user.id)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:success] = "Post created successfully."
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
    unless current_user.id == @post.user_id
      flash[:danger] = "You're not allowed to edit someone else post ?"
      redirect_to post_path(@post)
    end
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post updated successfully."
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:danger] = "Post deleted successfully"
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :category_id, :thumbnail)
  end

  def set_postid
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @cat %>
<%= form_for @cat do |c| %>
  <div class="form-group">
    <%= label_tag(:name, "Name:") %>
    <%= c.text_field :name, class: 'form-control', placeholder: 'Category Name' %>
  </div>
  <div class="form-group">
    <%= label_tag(:content, "Category Description:") %>
    <%= c.text_area :content, class: 'form-control', size: "10x10", placeholder: 'Category Description' %>
  </div>
  <%= c.submit(@cat.new_record? ? 'Publish' : "Update", class: 'btn btn-sm btn-primary') %>
  <%= link_to 'cancle', categories_path, class: 'btn btn-sm btn-danger' %>
<% end %>

app/views/categories/edit.html.erb
<div class="row my-5">
  <div class="col-md-12">
    <h3>Edit this category</h3>
    <%= render  "form" %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="row my-5">
  <div class="col-md-10">
    <table class="table table-striped table-dark">
      <thead class="thead-inverse">
        <tr>
          <th>Category ID</th>
          <th>Category Name</th>
          <th>Category Description</th>
          <th>Publish Time</th>
          <th>Action</th>
        </tr>
        </thead>
        <tbody>
          <% @cats.each do |c| %>
          <tr>
            <td scope="row"><%= c.id %></td>
            <td><%= c.name %></td>
            <td><%= c.content %></td>
            <td><%= c.created_at.strftime('%A, %b %d') %></td>
            <td>
              <div class="btn-group" role="group" aria-label="Basic example">
                <%= link_to  "View", category_path(c), class: 'btn btn-primary' %>
                <%= link_to  "Edit", edit_category_path(c), class: 'btn btn-secondary' %>
                <%= link_to  "Delete", category_path(c), method: :delete, data: {Confirm: "Are you sure?"}, class: 'btn btn-danger' %>
              </div>
            </td>
          </tr>
          <% end %>
        </tbody>
    </table>
  </div>
  <div class="col-md-2">
    <%= link_to  "Create New Category", new_category_path(@cat), class: 'btn btn-primary btn-sm' %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="row my-5">
  <div class="col-md-12">
    <h3>Create new category</h3>
    <%= render  "form" %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="row my-5">
  <div class="col-md-12">
    <%= @cat.name %>
    <%= @cat.content %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |c| %>
  <div class="form-group col-md-6">
    <%= c.label :name %>
    <%= c.text_field :name, class: "form-control", placeholder: 'Please enter your name.' %>
  </div>
  <div class="form-group col-md-12">
    <%= c.label :message %>
    <%= c.text_area :message, class: "form-control", placeholder: 'Please enter your Comment.', rows: '10' %>
  </div>
  <div class="form-group col-md-12">
    <%= c.submit :Publish, class: 'btn btn-sm btn-success' %>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<div class="alert alert-<%= "#{name}" %> alert-dismissible fade show mt-5" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    <span class="sr-only">Close</span>
  </button>
  <strong><%= msg %></strong>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render  "shared/navbar" %>
    <div class="container pt-5">
      <%= render  "layouts/messages" %>
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="jumbotron mt-5 bg-success text-center">
      <h1 class="display-3 font-weight-bold">Welcome to our About Page.</h1>
      <p class="lead">This is a simple blog built with ruby on rails. cause i love RoR!</p>
      <hr class="my-2">
      <p>More info</p>
      <p class="lead">
        <a class="btn btn-primary btn-sm" href="Jumbo action link" role="button">Sign Up</a>
      </p>
    </div>
  </div>
</div>
<% #end of jumbotron %>

app/views/pages/blog.html.erb
<div class="row mt-5">
  <% @posts.each do |post| %>
  <div class="col-md-8 offset-md-2 mb-5">
    <div class="card">
      <% if post.thumbnail.attached? %>
        <div class="bg-img">
          <%= image_tag post.thumbnail %>
        </div>
      <% else %>
        <div class="bg-img">
          <%= image_tag('Ruby_On_Rails_Logo.svg.png') %>
        </div>
      <% end %>
      <div class="card-body">
        <h4 class="card-title font-weight-bold"><%= link_to post.title, post_path(post) %></h4>
        <div class="content card-tex text-secondary">
          <%= post.content.html_safe %>
        </div>
      </div>
      <div class="card-footer">
        <div class="row">
          <div class="col-md-8">
            <span class="badge badge-secondary">Posted <%= time_ago_in_words(post.created_at) %> ago.</span>
            <strong>
              <span class="badge badge-secondary">In Category: <%= post.category.name %></span>
            </strong>
            <span class="badge badge-warning">Author: <%= post.user.username %></span>
          </div>
         
          <div class="col-md-4 text-right">
            <%= link_to 'View', post_path(post), class: 'badge badge-secondary' %>
            <% if user_signed_in? && current_user.id == post.user_id %>
              <%= link_to 'Edit', edit_post_path(post), class: 'badge badge-primary' %>
              <%= link_to 'Delete', post_path(post), method: :delete, data:{Confirm: "Are you sure?"}, class: 'badge badge-danger' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
<div class="row d-flex justify-content-center mt-5">
  <div class="col-6">
    <%= will_paginate @posts, 
      :list_classes => ['pagination justify-content-center'], 
      :aria_label => 'Page Navigation', 
      :previous_label => '&laquo;', 
      :next_label => '&raquo;' 
      %>
  </div>
</div>
<div class="row d-flex justify-content-center mt-5">
  <div class="col-6">
    <div class="bg-dark text-center text-white">
      <h6 class="mb-0 py-2">
        Total number of posts published: 
        <strong><%= @posts.count %></strong>
      </h6>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="row my-5">
  <div class="col-md-12">
    <form>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputEmail4">Email</label>
          <input type="email" class="form-control" id="inputEmail4" placeholder="Email">
        </div>
        <div class="form-group col-md-6">
          <label for="inputPassword4">Password</label>
          <input type="password" class="form-control" id="inputPassword4" placeholder="Password">
        </div>
      </div>
      <div class="form-group">
        <label for="inputAddress">Address</label>
        <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
      </div>
      <div class="form-group">
        <label for="inputAddress2">Address 2</label>
        <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputCity">City</label>
          <input type="text" class="form-control" id="inputCity">
        </div>
        <div class="form-group col-md-4">
          <label for="inputState">State</label>
          <select id="inputState" class="form-control">
            <option selected>Choose...</option>
            <option>...</option>
          </select>
        </div>
        <div class="form-group col-md-2">
          <label for="inputZip">Zip</label>
          <input type="text" class="form-control" id="inputZip">
        </div>
      </div>
      <div class="form-group">
        <div class="form-check">
          <input class="form-check-input" type="checkbox" id="gridCheck">
          <label class="form-check-label" for="gridCheck">
            Check me out
          </label>
        </div>
      </div>
      <div class="form-group">
        <label for="exampleFormControlTextarea1">Example textarea</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
      </div>
      <button type="submit" class="btn btn-primary">Sign in</button>
    </form>
  </div>
</div>

app/views/pages/home.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="jumbotron mt-5 bg-success text-center">
      <h1 class="display-3 font-weight-bold">Welcome to our blog.</h1>
      <p class="lead">This is a simple blog built with ruby on rails. cause i love RoR!</p>
      <hr class="my-2">
      <p>More info</p>
      <p class="lead">
        <%= link_to  "Sign Up", new_user_registration_path, class: 'btn btn-primary btn-sm' %>
      </p>
    </div>
  </div>
</div>
<% #end of jumbotron %>

<div class="row">
  <div class="col-md-12">
    <h2>Recent Posts</h2>
  </div>
</div>
<div class="row">
  <% @posts.each do |post| %>
  <div class="col-md-6 mb-5">
    <div class="card">
      <img class="card-img-top" src="holder.js/100px180/" alt="">
      <div class="card-body">
        <h4 class="card-title font-weight-bold">
          <%= link_to post.title, post_path(post) %>
        </h4>
        <div class="content card-tex text-secondary">
          <%= post.content.html_safe %>
        </div>
      </div>
      <div class="card-footer">
        <div class="row">
          <div class="col-md-8">
            <span class="badge badge-secondary">Posted 
              <%= time_ago_in_words(post.created_at) %> ago.
            </span>
            <strong>
              <span class="badge badge-secondary">In Category: 
                <%= post.category.name %>
              </span>
            </strong>
          </div>
          <div class="col-md-4 text-right">
            <%= link_to  "View", post_path(post), class: 'badge badge-secondary' %>
            <% if user_signed_in? && current_user.id == post.user_id %>
              <%= link_to  "Edit", edit_post_path(post), class: 'badge badge-primary' %>
              <%= link_to  "Delete", post_path(post), method: :delete, data: {Confirm: "Are you sure?"}, class: 'badge badge-danger' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= render  "shared/errors", obj: @post %>
<%= form_for @post do |f| %>
  <div class="form-group">
    <%= label_tag(:title, "Title:") %>
    <%= f.text_field :title, class: 'form-control', placeholder: 'Post title' %>
  </div>
  <div class="form-group">
    <%= label_tag(:thumbnail, "Thumbnail:") %>
    <%= f.file_field :thumbnail %>
  </div>
  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
    <%= link_to  "Create New Category", new_category_path(@category), class: 'btn btn-sm btn-primary' %>
  </div>
  <div class="form-group">
    <%= label_tag(:content, "Post Content:") %>
    <%= f.text_area :content, class: 'tinymce form-control', size: "10x10", placeholder: 'Post Content' %>
  </div>
  <%= f.submit(@post.new_record? ? 'Publish' : "Update", class: 'btn btn-sm btn-primary') %>
  <%= link_to 'cancle', posts_path, class: 'btn btn-sm btn-danger' %>
<% end %>
<%= tinymce %>

app/views/posts/edit.html.erb
<div class="row my-5">
  <div class="col-md-8 offset-md-2">
    <h1>Edit this post.</h1>
    <%= render  "form" %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="row my-5">
  <div class="col-md-12">
    <table class="table table-bordered table-striped table-inverse table-responsive">
      <thead class="thead-inverse">
        <tr>
          <th class="text-dark-50 text-center" width="10%">Post ID</th>
          <th class="text-dark-50 text-center">Post Title</th>
          <th class="text-dark-50 text-center">Post Content</th>
          <th class="text-dark-50 text-center">Category</th>
          <th class="text-dark-50 text-center" colspan="3">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
        <tr>
          <td scope="row" class="font-weight-bold">
            <%= post.id %>
          </td>
          <td class="font-weight-bold">
            <%= link_to post.title, post_path(post) %>
          </td>
          <td class="font-weight-bold">
            <div class="content card-tex font-weight-bold text-secondary">
              <%= post.content.html_safe %>
            </div>
          </td>
          <td><%= post.category && post.category.name %></td>
          
          <td class="font-weight-bold">
            <%= link_to 'View', post_path(post), class: 'btn btn-sm btn-success' %>
          </td>
          <% if user_signed_in? && current_user.id == post.user_id %>
          <td class="font-weight-bold">
            <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-sm btn-info' %>
          </td>
          <td class="font-weight-bold">
            <%= link_to 'Delete', post_path(post), method: :delete, data: {Confirm: "Are you sure?"}, class: 'btn btn-sm btn-danger' %>
          </td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row my-5">
  <div class="col-md-8 offset-md-2">
    <h1>Create new post.</h1>
    <%= render  "form" %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row my-5">
  <div class="col-md-10 offset-md-1">
    <h1 class="font-weight-bold"><%= @post.title %></h1>
    <article class="article text-secondary">
      <%= simple_format(@post.content) %>
    </article>
    <div class="col text-right">
      <% if user_signed_in? && current_user.id == @post.user_id %>
      <%= link_to 'Edit', edit_post_path(@post), class: 'badge badge-primary' %>
      <%= link_to 'Delete', post_path(@post), method: :delete, data:{Confirm: "Are you sure?"}, class: 'badge badge-danger' %>
      <% end %>
      <%= link_to 'Back To Blog', blog_path, class: 'badge badge-warning' %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-10 offset-md-1">
    <hr>
  </div>
</div>

<div class="row my-5">
  <div class="col-md-10 offset-md-1">
    <% @post.comments.each do |c| %>
      <div class="card text-left mb-3">
        <div class="card-body">
          <h4 class="card-title">Comment By: <%= c.name %></h4>
          <p class="card-text"><%= c.message %></p>
        </div>
        <div class="card-footer">
          <%= link_to 'Delete', post_comment_path(@post, c), method: :delete, data: {Confirm: "Are you sure?"}, class: 'btn btn-sm btn-danger' %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-md-10 offset-md-1">
    <div class="jumbotron bg-dark-light">
      <h3>Add Comment</h3>
      <%= render  "comments/form" %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">Close</span>
    </button>
    
    <h5>The following <%= pluralize(obj.errors.count, 'error') %> preventing this post to be saved!<h5>
    <% obj.errors.full_messages.each do |msg| %>
      <ul>
      <li><%= msg %></li>
      </ul>
    <% end %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-dark text-white">
  <div class="container">
    <div class="row justify-content-center text-center">
      <div class="col">
        <p class="mb-0 py-1">All right reserved &copy; 2019 smehsan.</p>
      </div>  
    </div>  
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">
  <div class="container">
    <%= link_to  "Branding", root_path, class: 'navbar-brand font-weight-bold' %>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-flex w-100" id="collapsibleNavId">
      <ul class="navbar-nav w-75 justify-content-end">
        <%= form_tag blog_path, :class => 'form-inline w-75', :method => 'get' do  %>
          <%= text_field_tag :search, '', class: 'form-control mr-sm-2 w-75', placeholder: 'Search' %>
          <%= submit_tag "Search", name: nil, class: 'btn btn-primary'%>
        <% end %>
      </ul>
      <ul class="navbar-nav w-50 justify-content-end">
        <li class="nav-item <%= 'active' if current_page?(root_path) %>">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(about_path) %>">
          <%= link_to 'About', about_path, class: 'nav-link' %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(blog_path) %>">
          <%= link_to 'Blog', blog_path, class: 'nav-link' %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(contact_path) %>">
          <%= link_to 'Contact', contact_path, class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if user_signed_in? && current_user %>
            <%= current_user.username %>
            <% else %>
            Action
            <% end %>
          </a>
          <div class="dropdown-menu" aria-labelledby="dropdownId">
            <% if user_signed_in? %>
              <%= link_to  "Create Post", new_post_path(@post), class: 'dropdown-item' %>
              <%= link_to  "Sign Out", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            <% else %>
              <%= link_to  "Sign In", new_user_session_path, class: 'dropdown-item' %>
              <%= link_to  "Sign Up", new_user_registration_path, class: 'dropdown-item' %>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>